esphome:
  name: freenove-display
  friendly_name: Freenove Display

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret freenove_display_api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Freenove-Display-Fallback"
    password: !secret fallback_password

captive_portal:
